headlines/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'headlines'
urlpatterns = [
    path('', views.index, name='index'),
    path('sentiment', views.chart_display, name = 'sentiment'),
    path('percent_news', views.chart_neg_pos, name = "percent_news"),
    path('keyword_cloud', views.keyword_cloud, name = 'keyword_cloud'),
    path('headline_filter/<str:word>/', views.headline_display, name = 'headline_filter'),
    path('keyword_list', views.keyword_display, name = "keyword_list"),
    path('news_websites/', views.news_websites, name='news_websites'),
    path('about/', views.about, name='about'),
    path('process/', views.process, name='process')
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

news_analysis_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('headlines/', include('headlines.urls')),
    path('admin/', admin.site.urls),
]

headlines/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Headline(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    content = models.CharField(db_column='Content', max_length=255)  # Field name made lowercase.
    datetime = models.DateTimeField(db_column='Datetime', blank=True, null=True)  # Field name made lowercase.
    vader = models.FloatField(db_column='Vader', blank=True, null=True)  # Field name made lowercase.
    liuhu = models.FloatField(db_column='LiuHu', blank=True, null=True)  # Field name made lowercase.
    newssourceid = models.ForeignKey('Newssource', models.DO_NOTHING, db_column='NewsSourceId')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Headline'


class Headlinekeyword(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    headlineid = models.ForeignKey(Headline, models.DO_NOTHING, db_column='HeadlineId')  # Field name made lowercase.
    keywordid = models.ForeignKey('Keyword', models.DO_NOTHING, db_column='KeywordId')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'HeadlineKeyword'


class Keyword(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    content = models.CharField(db_column='Content', max_length=255)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Keyword'


class Newssource(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=255)  # Field name made lowercase.
    url = models.CharField(db_column='Url', max_length=255)  # Field name made lowercase.

    class Meta:
        managed = False
        
        db_table = 'NewsSource'

headlines/views.py
from django.shortcuts import render
from django.template import loader
from .models import Newssource

# Create your views here.
from django.http import HttpResponse, Http404

from .sentiment_extractor import SentimentExtractor
from .keyword_retriever import KeywordRetriever
from .headline_retriever import HeadlineRetriever

def chart_display(request):
	sent_extractor = SentimentExtractor()
	info = sent_extractor.get_all_news_sources()

	mylabels = info[0]
	mydata = info[1]
	vader_data = sent_extractor.get_all_news_source_vader_values()

	context = {'my_perc_labels':mylabels, 
			   'my_perc_data':mydata,
			   'my_hist_data':vader_data}

	return render(request, 'headlines/chart_display.html', context)

def chart_neg_pos(request):
	sent_extractor = SentimentExtractor()

	vader_data = sent_extractor.get_all_news_source_vader_values()
	return render(request, 'headlines/chart_neg_pos.html', {'my_hist_data':vader_data})

def keyword_cloud(request):
	keyword_retriever = KeywordRetriever()
	info = keyword_retriever.keyword_frequencies(limit = 150)
	return render(request, 'headlines/keyword_cloud.html', {'mydata':info})

def headline_display(request, word):
	try:
		hr = HeadlineRetriever()
		headlines = hr.get_headlines()
		news_sources = ["abc", "nbc", "fox", "reuters"]
		months = ['January', 'February', 'March', 'April', 'May', 'June', 
				  'July', 'August', 'September', 'October', 'November', 'December']
		days = list(range(1, 32))

	except:
		raise Http404("Keyword does not exist!")
	
	context = {'kw': word, 
				'headlines': headlines, 
				'newssources': news_sources,
				'months': months,
				'days': days}
	return render(request, 'headlines/display_headlines.html', context)

def keyword_display(request):
	kr = KeywordRetriever()
	info = kr.keyword_frequencies()
	context = {"kws": info}

	return render(request, 'headlines/keyword_list.html', context)

def index(request):
	template = loader.get_template('headlines/home.html')
	context = {}
	return HttpResponse(template.render(context, request))

def news_websites(request):
    news_list = Newssource.objects.all()
    template = loader.get_template('headlines/news_websites.html')
    context = {
        'news_list': news_list,
    }
    return HttpResponse(template.render(context, request))

def about(request):
    template = loader.get_template('headlines/about.html')
    context = {
    }
    return HttpResponse(template.render(context, request))

def process(request):
    news_list = Newssource.objects.all()
    template = loader.get_template('headlines/process.html')
    context = {
        'news_list': news_list,
    }
    return HttpResponse(template.render(context, request))

headlines/templates/headlines/about.html
<!DOCTYPE html>
<html>
  <head>
    <title>About Page</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>

  <body>

    <div id = "navigation-bar">
      {% include 'headlines/navigation_bar.html' %}
    </div>

    <div class="container-fluid">

        <div class="page-header">
            <h2>About Us</h2>
        </div>
    
      <h4>Who We Are</h4>

      <p>We are two bored programmers looking for things to do over the summer during the COVID-19 pandemic.</p>

      <br>
    
      <h4>Purpose</h4>

      <p>This project was created to practiced using data analysis on real world data. Because we were interested in seeing how biases differ between news sources, our project focused on gathering data from news headlines.</p>

      <br>
    </div>


    <div class = "text-center">
        <p></p>
        <p>Copyright 2020 ©  All rights reserved. Don't Copy our CODE</p>
    </div>
  </body>
</html>

headlines/templates/headlines/chart_display.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Chart Display</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

	<script src="{% static 'headlines/chart_generator.js' %}"></script>
	<script src='https://cdn.plot.ly/plotly-latest.min.js'></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>
<body>
	<div id = "navigation-bar">
      {% include 'headlines/navigation_bar.html' %}
    </div>

	<div class="container">
	  <h2>Sentiment Analysis</h2>
	  <p>The Vader method was used to calculate the sentiment value of each headline.</p>
<!-- 	  <p>To make the tabs toggleable, add the data-toggle="tab" attribute to each link. Then add a .tab-pane class with a unique ID for every tab and wrap them inside a div element with class .tab-content.</p> -->

	  <ul class="nav nav-tabs">
	    <li class="active"><a data-toggle="tab" href="#home">Menu</a></li>
	    <li><a data-toggle="tab" href="#menu1">Percentage Bar Graph</a></li>
	    <li><a data-toggle="tab" href="#menu2">Sentiment Range Histogram</a></li>
<!-- 	    <li><a data-toggle="tab" href="#menu3">Menu 3</a></li> -->
	  </ul>

	  <div class="tab-content">
	    <div id="home" class="tab-pane fade in active">
	      <h3>Menu</h3>

	      <p>The following graphs are available for sentiment analysis. The data was first collected on June 24, 2020.</p>

	      <ul>
	      	<li>Percent bar graph - This bar graph shows the percent of headlines that are positive, neutral, or negative for headlines of selected sources.</li>
	      	<li>Sentiment range histogram - This histogram shows the range of sentiment values for headlines of selected sources.
	      </ul>
	    </div>
	    <div id="menu1" class="tab-pane fade">
	      <div>
	      	{% include 'headlines/chart_templates/chart_percent_graph.html' %}
	      </div>
	    </div>
	    <div id="menu2" class="tab-pane fade">
	      <div>
	      	{% include 'headlines/chart_templates/chart_hist.html' %}
	      </div>
	    </div>
<!-- 	    <div id="menu3" class="tab-pane fade">
	      <h3>Menu 3</h3>
	      <p>Eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
	    </div> -->
	  </div>
	</div>


</body>
</html>

headlines/templates/headlines/chart_neg_pos.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Sentiment Analysis</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

	<script src="{% static 'headlines/chart_generator.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>
<body>

	<div class = "text-center">
		<h1>Sentiment Analysis</h1>
		<p>These sentiment values are based on all headlines gathered since June 24, 2020.</p>
		<button id="button1" class="btn btn-primary">Generate Graph</button>
		<div>
			{% for key in mydata%}
				<input type="checkbox" id = "checkbox_{{key}}" name="{{key}}" class="form-check">
				<label for="{{key}}">{{key}}</label>
			{% endfor %}
		</div>
	</div>
	

	<canvas id = "chart1"></canvas>
	<script>
		var ctx = document.getElementById('chart1').getContext('2d');
		var button1 = document.getElementById('button1');

		button1.onclick = function() {myFunction(ctx)};

		function myFunction(ctx){
			var datasets = {{mydata|safe}};
			var colors = ['red', 'orange', 'green', 'blue', 'purple'];
			var bar_inputs = [];
			var idx = 0;

			for(var key in datasets){
				var isChecked = document.getElementById('checkbox_' + key).checked

				if (isChecked){
					var input = {
						label: key,
						backgroundColor: colors[idx],
						borderColor: colors[idx],
						data: datasets[key]
					};
					bar_inputs.push(input);
				}

				idx +=1;
			}

			var chart = new Chart(ctx, {
				//the type of chart we want to create
				type : 'bar',

				//the data
				data:{
					labels: {{mylabels|safe}},
					datasets : bar_inputs,
				},

				//config options
				options: {
					title:{
						display: true,
						text: 'Percentage of Headlines in Each Sentiment Category',
						fontSize: 30
					},
					scales:{
						xAxes:[{
							scaleLabel:{
								display: true,
								labelString: 'Sentiment',
								fontSize: 20
							}
						}],
						yAxes:[{
							scaleLabel:{
								display: true,
								labelString: 'Percent',
								fontSize : 20
							},
							ticks : {
								beginAtZero: true
							}
						}]
					}
				}
			});
		}
	</script>
</body>
</html>

headlines/templates/headlines/chart_templates/chart_hist.html
<div>
	<div class="container">
		<div class="text-center">
			<h1>Sentiment Range Histogram</h1>

			<button id="button1" class="btn btn-primary">Generate Graph</button>
			<div>
				{% for key in my_hist_data%}
					<input type="checkbox" id = "checkbox_{{key}}" name="{{key}}" class="form-check">
					<label for="{{key}}">{{key}}</label>
				{% endfor %}
			</div>

		</div>

		<div id = "myDiv"></div>
	</div>

	<script type="text/javascript">

		var button1 = document.getElementById('button1');
		var data = {{my_hist_data|safe}};

		button1.onclick = function() {generate_graph(data)};

		function generate_graph(data) {
			var colors = ["purple", "orange", "green", "blue", ];

			var traces = []
			var index = 0; 

			for(var key in data){

				var isChecked = document.getElementById('checkbox_' + key).checked

				if(isChecked){
					trace = {x: data[key],
							 name: key,
							 autobinx: false,
							 histnorm: "probability",
							 marker: {
							 	color: colors[index],
							 	line: {
							 		color: colors[index],
							 		width: 1
							 	}
							 },
							 opacity: 0.5,
							 type: "histogram",
							 xbins: {
							 	end: 1.0,
							 	size: 0.01,
							 	start: -1.0
							 }
					};
					traces.push(trace);
				}
				
				index += 1;
			}

			var layout = {
			  font: {
			  	family: 'Arial'
			  },
			  bargap: 0.0, 
			  barmode: "overlay", 
			  title: "", 
			  xaxis: {title: "Sentiment Value"}, 
			  yaxis: {title: "Percent Number of Headlines for Each News Source"}
			};
			Plotly.newPlot('myDiv', traces, layout);
		}
	</script>
</div>

headlines/templates/headlines/chart_templates/chart_percent_graph.html
<div>
	<div class="container">
		<div class = "text-center">
			<h1>Percent Bar Graph</h1>
			<button id="button2" class="btn btn-primary">Generate Graph</button>
			<div>
				{% for key in my_perc_data%}
					<input type="checkbox" id = "checkbox_{{key}}2" name="{{key}}" class="form-check">
					<label for="{{key}}">{{key}}</label>
				{% endfor %}
			</div>
		</div>
		<div id = "chart1"></div>
	</div>
	
	<script>
		var button1 = document.getElementById('button2');
		var datasets = {{my_perc_data|safe}};

		button1.onclick = function() {myFunction(datasets)};

		function myFunction(datasets){
			
			var colors = ['purple', 'orange', 'green', 'blue'];
			var bar_inputs = [];
			var idx = 0;

			for(var key in datasets){
				var isChecked = document.getElementById('checkbox_' + key+'2').checked

				if (isChecked){
					var input = {
						x: {{my_perc_labels|safe}},
						y: datasets[key],
						name: key,
						type: "bar",
						marker: {
							 	color: colors[idx],
							 	line: {
							 		color: colors[idx],
							 		width: 1
							 	}
							 }
					};
					bar_inputs.push(input);
				}

				idx +=1;
			}

			var layout = {
			  font: {
			  	family: 'Arial'
			  }, 
			  barmode: "group", 
			  title: "", 
			  xaxis: {title: "Sentiment Classification"}, 
			  yaxis: {title: "Percent Number of Headlines for Each News Source"}
			};
			Plotly.newPlot('chart1', bar_inputs, layout);

		}
	</script>
</div>

headlines/templates/headlines/home.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Home Page</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <style type="text/css">
      .jumbotron {
        background-image: linear-gradient(to bottom, rgba(255,255,255,0.9) 0%,rgba(255,255,255,0.9) 100%), url("{% static 'headlines/website_header_image.PNG' %}");
        background-size: auto 100%;
      }
      h1 {
        text-shadow: 0 0 20px #337ab7;
      }
    </style>
  </head>

  <body>
    
    <div id = "navigation-bar">
      {% include 'headlines/navigation_bar.html' %}
    </div>

    <div class="container-fluid">
      <div class="jumbotron text-center">
        <h1>Welcome to Newslytics</h1>
        <h3>Check out our tools to analyze media headlines!</h3>
      </div>
      
      <div class="row">
        <div class="col-sm-6">
          <div class="well" style="background-color: #f7b783;">
            <div class="card">
              <img src="https://img.icons8.com/wired/64/000000/bar-chart.png" style="margin-left:43%;"/>
              <div class="card-body text-center">
                <h2 class="card-title"><b>Sentiment Analysis Charts</b></h2>
                <p class="card-text">Bar graphs that compare sentiment values of headlines from multiple news sources</p>
                <a href="{% url 'headlines:sentiment' %}" class="btn btn-primary">See Charts</a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="well" style="background-color: #83c7f7;">
            <div class="card">
              <img src="https://img.icons8.com/wired/64/000000/cloud.png" style="margin-left:43%;"/>
              <div class="card-body text-center">
                <h2 class="card-title"><b>Hot Topics Word Cloud</b></h2>
                <p class="card-text">Word cloud that shows most popular topics in new headlines from multiple sources</p>
                <a href="{% url 'headlines:keyword_cloud' %}" class="btn btn-primary">See Word Cloud</a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="well" style="background-color: #d8f582;">
            <div class="card">
              <img src="https://img.icons8.com/dotty/80/000000/search-bar.png" style="margin-left:43%;"/>
              <div class="card-body text-center">
                <h2 class="card-title"><b>Search Headlines</b></h2>
                <p class="card-text">Search engine that returns list of headlines related to a given topic</p>
                <a href="{% url 'headlines:headline_filter' 'NONE' %}" class="btn btn-primary">See Search Engine</a>
              </div>
            </div>
          </div>
        </div>
      </div>


      <div class = "text-center">
        <p></p>
        <p>Copyright 2020 ©  All rights reserved. Don't Copy our CODE</p>
      </div>

    </div>

  </body>
</html>

headlines/templates/headlines/keyword_cloud.html
{% load static%}
<!DOCTYPE html>
<html>
<head>
	<title>Keyword Cloud</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	
	<script src="{% static 'headlines/wordcloud_generator.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <style type="text/css">
    	.page-header{
    		text-align: center;
    	}
    	.header-style{
    		text-align: center;
    	}
    	#button-change{
    		margin: 10px;
    	}
    </style>
</head>
<body>
	
	<div id = "navigation-bar">
      {% include 'headlines/navigation_bar.html' %}
    </div>

    <div class="container">
    	<div class="page-header">
            <h1>Keyword Cloud</h1>
            <br>
            <p>Hover over word in cloud to see keyword. To see total list of keywords click on the button below. To see all headlines for a given keyword, click on the keyword in the cloud.</p>
        </div>
    	<div class="header-style">
    		<button class="btn btn-primary" onclick="go_to_list()" id="button-change">Go to List</button>
    		<h3 id = "keywordtext" style="display: inline-block;"></h3>
    	</div>
		<canvas id="cloud1" width="1200" height="700"></canvas>
    </div>
	
	<script>

		function go_to_list(argument) {
			var url = "{% url 'headlines:keyword_list' %}"
			window.location.href = url;
		}

		WordCloud(document.getElementById('cloud1'), 
			{list: {{mydata|safe}},
			 gridSize: 8,
			 shape: 'square',
			 hover: hover_over,
			 click: click_trigger,
			 color: "random-light",
			 backgroundColor: "black"
			});

		function click_trigger(item, dimension, event) {
			var url = "{% url 'headlines:headline_filter' 'foobar' %}".replace("foobar", item[0]);
			window.open(url);
		}

		function hover_over(item, dimension, event){

			document.getElementById("keywordtext").innerHTML = "Current keyword is " + item[0]; 
		}
	</script>

	<br>
	<br>
	<p class = "text-center">*Note: Data based on headlines retrieved since June 24, 2020.</p>
</body>
</html>

headlines/templates/headlines/keyword_list.html
<!DOCTYPE html>
<html>
<head>
	<title>Keyword Table</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

	<!-- Data Table Source Code -->
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
</head>
<body>
	<div id = "navigation-bar">
      {% include 'headlines/navigation_bar.html' %}
    </div>

    <div class="container">
    	<div class="page-header text-center">
            <h1>Keyword List</h1>
        </div>
    	
    	<button class="btn btn-primary" id="button-change" style="margin: 10px;">Go to WordCloud</button>

    	<table class="table table-striped table-bordered" id="keyword_table">
    		<thead>
    			<th scope="col">#</th>
    			<th scope="col">Keyword</th>
    			<th scope="col">Number of Headlines</th>
    		</thead>
    		<tbody>
    			{% for kw in kws%}
    				<tr>
    					<th>{{forloop.counter}}</th>
    					<td>{{kw.0}}</td>
    					<td>{{kw.1}}</td>
    				</tr>
    			{% endfor %}
    		</tbody>
    	</table>
    </div>

    <script type="text/javascript">
    	$(document).ready(function () {
    		$("#keyword_table").DataTable();
    		$("#button-change").on("click", function(){
    			var url = "{% url 'headlines:keyword_cloud' %}"
    			window.location.href = url; 
    		});
    	});
    </script>

    <br>
    <br>
    <p class = "text-center">*Note: Data based on headlines retrieved since June 24, 2020.</p>
</body>
</html>

headlines/templates/headlines/navigation_bar.html
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'headlines:index' %}">Newslytics</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'headlines:process' %}">Our Process <span class="sr-only">(current)</span></a></li>
        <li><a href="{% url 'headlines:about' %}">About Us</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tools <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'headlines:sentiment' %}">Sentiment Analysis Comparison</a></li>
            <li><a href="{% url 'headlines:keyword_cloud' %}">Hot Topics Word Cloud</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'headlines:headline_filter' 'NONE' %}">Search Topics</a></li>
          </ul>
        </li>
      </ul>
<!--       <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

headlines/templates/headlines/news_websites.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My test page</title>
  </head>
  <body>
    <p>
        {% if news_list %}
            <ul>
            {% for news in news_list %}
                <li><a href="{{ news.url }}">{{ news.name }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>Unable to show list of news sources!</p>
        {% endif %}
    </p>
  </body>
</html>